UPDATE colaboradores SET dataNascimento = '2001-01-07' WHERE UPPER(nome) = 'VITOR BERLINK SANTOS';
UPDATE colaboradores SET dataNascimento = '1992-02-02' WHERE UPPER(nome) = 'ANDERSON LUIS SANTOS SILVA';
UPDATE colaboradores SET dataNascimento = '1980-01-09' WHERE UPPER(nome) = 'EMMANUEL DE OLIVEIRA MONTEIRO';
UPDATE colaboradores SET dataNascimento = '1990-02-03' WHERE UPPER(nome) = 'LOURINALDO SILVA CORDEIRO DE PONTES';
UPDATE colaboradores SET dataNascimento = '1981-01-09' WHERE UPPER(nome) = 'ANDRE SANTOS NERI';
UPDATE colaboradores SET dataNascimento = '1989-02-08' WHERE UPPER(nome) = 'RAMON PARAGUASSU RANGEL CARDOSO';
UPDATE colaboradores SET dataNascimento = '1986-01-13' WHERE UPPER(nome) = 'TAMARA SOARES CARVALHO';
UPDATE colaboradores SET dataNascimento = '1998-02-10' WHERE UPPER(nome) = 'WELLINGTON GAUTAMA COSTA BORGES JUNIOR';
UPDATE colaboradores SET dataNascimento = '1994-01-15' WHERE UPPER(nome) = 'VIRLANNE GOMES DE ANDRADE';
UPDATE colaboradores SET dataNascimento = '1987-02-11' WHERE UPPER(nome) = 'DOUGLAS SANTOS GUIMARAES';
UPDATE colaboradores SET dataNascimento = '1996-01-15' WHERE UPPER(nome) = 'MARCELO SILVA SOUZA';
UPDATE colaboradores SET dataNascimento = '1998-02-12' WHERE UPPER(nome) = 'YAN FREIRE DA SILVA CERQUEIRA';
UPDATE colaboradores SET dataNascimento = '2002-01-17' WHERE UPPER(nome) = 'JOAO HENRIQUE DE SOUZA SANTOS';
UPDATE colaboradores SET dataNascimento = '2006-02-13' WHERE UPPER(nome) = 'GABRIEL BOMFIM DE OLIVEIRA';
UPDATE colaboradores SET dataNascimento = '2003-01-22' WHERE UPPER(nome) = 'BEATRIZ PAULINA PEREIRA RABELO';
UPDATE colaboradores SET dataNascimento = '1984-02-13' WHERE UPPER(nome) = 'ROSANA MARIA SANTOS SANTANA';
UPDATE colaboradores SET dataNascimento = '1989-01-24' WHERE UPPER(nome) = 'JOSE EDUARDO DOS SANTOS NUNES';
UPDATE colaboradores SET dataNascimento = '1987-02-16' WHERE UPPER(nome) = 'MABIANA ADRADE DE SOUZA';
UPDATE colaboradores SET dataNascimento = '1999-01-25' WHERE UPPER(nome) = 'ALAN ROBSON DE BARROS JUNIOR';
UPDATE colaboradores SET dataNascimento = '1984-02-28' WHERE UPPER(nome) = 'DAVI SANTOS BORGENS';
UPDATE colaboradores SET dataNascimento = '2000-01-26' WHERE UPPER(nome) = 'MARCOS GABRIEL SANTANA DOS SANTOS';
UPDATE colaboradores SET dataNascimento = '1988-01-29' WHERE UPPER(nome) = 'JERONIMO SOARES CHAVES';
UPDATE colaboradores SET dataNascimento = '2001-01-30' WHERE UPPER(nome) = 'JAVAN GUIMARAES SALES OLIVEIRA';
UPDATE colaboradores SET dataNascimento = '1986-01-31' WHERE UPPER(nome) = 'GERIEL DOS SANTOS CASTRO SOARES';
UPDATE colaboradores SET dataNascimento = '2004-01-31' WHERE UPPER(nome) = 'HENRIQUE MOURA VIANA';
UPDATE colaboradores SET dataNascimento = '1967-03-01' WHERE UPPER(nome) = 'JOSE ALVES DE JESUS';
UPDATE colaboradores SET dataNascimento = '1991-04-02' WHERE UPPER(nome) = 'MATHEUS DUMAS OLIVEIRA';
UPDATE colaboradores SET dataNascimento = '1999-03-01' WHERE UPPER(nome) = 'EDSON ALEXANDRINO DOS SANTOS JUNIOR';
UPDATE colaboradores SET dataNascimento = '1973-04-03' WHERE UPPER(nome) = 'MARIA DO CARMO DE J S COUTO';
UPDATE colaboradores SET dataNascimento = '1996-03-05' WHERE UPPER(nome) = 'YURI FERREIRA TORRES';
UPDATE colaboradores SET dataNascimento = '1975-04-04' WHERE UPPER(nome) = 'MARINEIDE DE JESUS SILVA';
UPDATE colaboradores SET dataNascimento = '2001-03-06' WHERE UPPER(nome) = 'MARIO HENRIQUE DE OLIVEIRA LOUREIRO';
UPDATE colaboradores SET dataNascimento = '1982-04-06' WHERE UPPER(nome) = 'REINALDO LIMA SOARES';
UPDATE colaboradores SET dataNascimento = '2003-03-07' WHERE UPPER(nome) = 'TIAGO CAMBRAINHA ARAÚJO';
UPDATE colaboradores SET dataNascimento = '1999-04-06' WHERE UPPER(nome) = 'LARISSA ALVES MENEZES';
UPDATE colaboradores SET dataNascimento = '1988-03-09' WHERE UPPER(nome) = 'DIOGO SANTOS GUIMARAES';
UPDATE colaboradores SET dataNascimento = '1997-04-08' WHERE UPPER(nome) = 'MARCEL DE OLIVEIRA SOUZA';
UPDATE colaboradores SET dataNascimento = '2004-03-10' WHERE UPPER(nome) = 'KAIQUE PEREIRA DOS SANTOS';
UPDATE colaboradores SET dataNascimento = '1980-04-09' WHERE UPPER(nome) = 'MARCELO SILVA SANTOS';
UPDATE colaboradores SET dataNascimento = '1996-03-11' WHERE UPPER(nome) = 'FELLIPE NARDE OLIVEIRA DA HORA';
UPDATE colaboradores SET dataNascimento = '1980-04-10' WHERE UPPER(nome) = 'FELIPE DE SA FALCÃO';
UPDATE colaboradores SET dataNascimento = '2008-03-11' WHERE UPPER(nome) = 'JOÃO VITOR PRATES CERQUEIRA';
UPDATE colaboradores SET dataNascimento = '1974-04-10' WHERE UPPER(nome) = 'MARCO ANTONIO OLIVEIRA RIBEIRO';
UPDATE colaboradores SET dataNascimento = '2004-03-11' WHERE UPPER(nome) = 'KAILAN DE SOUZA DIAS';
UPDATE colaboradores SET dataNascimento = '1995-04-14' WHERE UPPER(nome) = 'ROMEU DIAS ROCHA';
UPDATE colaboradores SET dataNascimento = '1978-03-12' WHERE UPPER(nome) = 'JORGE ASSIS SANTANA JUNIOR';
UPDATE colaboradores SET dataNascimento = '1977-04-16' WHERE UPPER(nome) = 'FABRICIO MACEDO SANTANA';
UPDATE colaboradores SET dataNascimento = '1983-03-13' WHERE UPPER(nome) = 'RICARDO HENRIQUE MONTEIRO DOS SANTOS';
UPDATE colaboradores SET dataNascimento = '1972-04-17' WHERE UPPER(nome) = 'CLAUDIO LUIZ DE OLIVEIRA';
UPDATE colaboradores SET dataNascimento = '1986-03-14' WHERE UPPER(nome) = 'WILLMS SANTOS SILVA';
UPDATE colaboradores SET dataNascimento = '2003-04-17' WHERE UPPER(nome) = 'YANA BARRETO LUIZ SIMINA';
UPDATE colaboradores SET dataNascimento = '1990-03-14' WHERE UPPER(nome) = 'TALITA OLIVEIRA GOMES';
UPDATE colaboradores SET dataNascimento = '1999-04-19' WHERE UPPER(nome) = 'TAINA NERI XAVIER DA SILVA SANTOS';
UPDATE colaboradores SET dataNascimento = '2000-03-15' WHERE UPPER(nome) = 'LEONARDO CARVALHO DE OLIVEIRA';
UPDATE colaboradores SET dataNascimento = '1982-04-20' WHERE UPPER(nome) = 'CLEISON SANTANA GOMES';
UPDATE colaboradores SET dataNascimento = '1988-03-17' WHERE UPPER(nome) = 'FERNANDO LIMA RODRIGUES';
UPDATE colaboradores SET dataNascimento = '1988-04-21' WHERE UPPER(nome) = 'CASSIO OLIVIER PEREIRA CIMA';
UPDATE colaboradores SET dataNascimento = '1969-03-24' WHERE UPPER(nome) = 'RONALDO SANTOS SACRAMENTO';
UPDATE colaboradores SET dataNascimento = '1979-04-22' WHERE UPPER(nome) = 'DANILO DE SOUZA FARIAS';
UPDATE colaboradores SET dataNascimento = '1973-03-25' WHERE UPPER(nome) = 'JORGE DE MORAES';
UPDATE colaboradores SET dataNascimento = '1983-04-24' WHERE UPPER(nome) = 'JEFERSON SUNDERLANDE DE OLIVEIRA';
UPDATE colaboradores SET dataNascimento = '1998-03-25' WHERE UPPER(nome) = 'GUILHERME DE SOUZA DORTAS MATOS';
UPDATE colaboradores SET dataNascimento = '1979-04-25' WHERE UPPER(nome) = 'MILENA DE ANDRADE';
UPDATE colaboradores SET dataNascimento = '1997-03-26' WHERE UPPER(nome) = 'JACKSON SANTOS NASCIMENTOS';
UPDATE colaboradores SET dataNascimento = '1983-04-28' WHERE UPPER(nome) = 'DANIELA VILAS BOAS BARBOSA';
UPDATE colaboradores SET dataNascimento = '1987-03-27' WHERE UPPER(nome) = 'MURILLO BATISTA FERNADES';
UPDATE colaboradores SET dataNascimento = '1999-03-27' WHERE UPPER(nome) = 'CAMILA SANTOS REIS';
UPDATE colaboradores SET dataNascimento = '1988-05-02' WHERE UPPER(nome) = 'MAYANA LIMA DOS SANTOS';
UPDATE colaboradores SET dataNascimento = '1984-06-01' WHERE UPPER(nome) = 'IELDER OLIVEIRA CARNEIRO';
UPDATE colaboradores SET dataNascimento = '1996-05-02' WHERE UPPER(nome) = 'ISRAEL DOS SANTOS XAVIER';
UPDATE colaboradores SET dataNascimento = '1987-06-03' WHERE UPPER(nome) = 'VIVIANE GOMES DE ANDRADE';
UPDATE colaboradores SET dataNascimento = '2002-05-03' WHERE UPPER(nome) = 'ISAAC MARQUES WANDERLAY';
UPDATE colaboradores SET dataNascimento = '1989-06-04' WHERE UPPER(nome) = 'NADJA ALINE SOARES LARANJADA';
UPDATE colaboradores SET dataNascimento = '1973-05-04' WHERE UPPER(nome) = 'RICARDO TRINDADE';
UPDATE colaboradores SET dataNascimento = '1997-06-04' WHERE UPPER(nome) = 'SHEILA MACEDO DA SILVA';
UPDATE colaboradores SET dataNascimento = '1960-05-11' WHERE UPPER(nome) = 'GRIMALDO TOSTENBERG SILVA';
UPDATE colaboradores SET dataNascimento = '2000-06-07' WHERE UPPER(nome) = 'LUAN VITOR DE SA BORGES';
UPDATE colaboradores SET dataNascimento = '1957-05-12' WHERE UPPER(nome) = 'DIJALMA GUIMARÃES PASSOS SALES';
UPDATE colaboradores SET dataNascimento = '2000-06-09' WHERE UPPER(nome) = 'HANAH PASSOS CANEIRO';
UPDATE colaboradores SET dataNascimento = '1982-05-12' WHERE UPPER(nome) = 'LEIDIANE DOS SANTOS';
UPDATE colaboradores SET dataNascimento = '1995-06-13' WHERE UPPER(nome) = 'ANTONIO SAMIR SOUZA';
UPDATE colaboradores SET dataNascimento = '1979-05-13' WHERE UPPER(nome) = 'THIAGO LIMA CEDRAZ';
UPDATE colaboradores SET dataNascimento = '2003-06-14' WHERE UPPER(nome) = 'LUCAS DANIEL SANTOS BEZERRA';
UPDATE colaboradores SET dataNascimento = '1982-05-16' WHERE UPPER(nome) = 'JUACI CARLOS SAMPAIO FILHO';
UPDATE colaboradores SET dataNascimento = '1991-06-17' WHERE UPPER(nome) = 'UALLAS CARLOS ANDRADE FONTES';
UPDATE colaboradores SET dataNascimento = '1988-05-16' WHERE UPPER(nome) = 'JOSE ALBERTO DA SILVA NASCIMENTO';
UPDATE colaboradores SET dataNascimento = '2000-06-19' WHERE UPPER(nome) = 'BRENO ASSUNÇÃO DE OLIVEIRA DE JESUS';
UPDATE colaboradores SET dataNascimento = '1993-05-17' WHERE UPPER(nome) = 'LEONARDO SOUSA FRAGA SANTOS';
UPDATE colaboradores SET dataNascimento = '1977-06-19' WHERE UPPER(nome) = 'NELSON REGINALDO DE BARROS FILHO';
UPDATE colaboradores SET dataNascimento = '1965-05-18' WHERE UPPER(nome) = 'IRAMIR FREIRE RIBEIRO';
UPDATE colaboradores SET dataNascimento = '1966-06-19' WHERE UPPER(nome) = 'NILTON DE SANTANA';
UPDATE colaboradores SET dataNascimento = '1985-05-22' WHERE UPPER(nome) = 'ALEXANDRE OLIVEIRA FREITAS';
UPDATE colaboradores SET dataNascimento = '1999-06-22' WHERE UPPER(nome) = 'CAIO NOVAIS DOS SANTOS';
UPDATE colaboradores SET dataNascimento = '1983-05-25' WHERE UPPER(nome) = 'CIRO SOUZA DA SILVA';
UPDATE colaboradores SET dataNascimento = '1995-06-25' WHERE UPPER(nome) = 'IALI SÂMIA BARBOSA RAMOS';
UPDATE colaboradores SET dataNascimento = '1975-05-28' WHERE UPPER(nome) = 'NEILTON COSTA MAIA';
UPDATE colaboradores SET dataNascimento = '2000-06-26' WHERE UPPER(nome) = 'DANIEL SOUZA DE OLIVEIRA';
UPDATE colaboradores SET dataNascimento = '1967-05-30' WHERE UPPER(nome) = 'ROBSON ANTONIO OLIVEIRA DE SOUZA';
UPDATE colaboradores SET dataNascimento = '1975-06-29' WHERE UPPER(nome) = 'JOSIMEIRE ALMEIDA MOURA';
UPDATE colaboradores SET dataNascimento = '2025-07-04' WHERE UPPER(nome) = 'WEDSON ANDRADE FREIRE';
UPDATE colaboradores SET dataNascimento = '2005-08-04' WHERE UPPER(nome) = 'LUIZ ARTHUR TAVARES DE BARROS';
UPDATE colaboradores SET dataNascimento = '1994-07-06' WHERE UPPER(nome) = 'FELIPE GONÇALVES DE OLIVEIRA NETO';
UPDATE colaboradores SET dataNascimento = '1995-08-05' WHERE UPPER(nome) = 'TIAGO SANTOS DA CONCEIÇÃO';
UPDATE colaboradores SET dataNascimento = '2003-07-08' WHERE UPPER(nome) = 'GEOVANA MICKAELA CAMPOS AMORIM';
UPDATE colaboradores SET dataNascimento = '2002-08-06' WHERE UPPER(nome) = 'YURI CARVALHO FEITOSA';
UPDATE colaboradores SET dataNascimento = '2002-07-11' WHERE UPPER(nome) = 'JUAN LUIS SOUZA BARBOSA';
UPDATE colaboradores SET dataNascimento = '2001-08-15' WHERE UPPER(nome) = 'MARCO ANTONIO BARRETO DOS SANTOS';
UPDATE colaboradores SET dataNascimento = '1998-07-11' WHERE UPPER(nome) = 'ANDRE LUIZ SILVA DO CARMO';
UPDATE colaboradores SET dataNascimento = '1994-08-18' WHERE UPPER(nome) = 'IOLANDA SOUZA REIS';
UPDATE colaboradores SET dataNascimento = '1991-07-11' WHERE UPPER(nome) = 'SAMELE BIAGGI PARENTE';
UPDATE colaboradores SET dataNascimento = '1995-08-21' WHERE UPPER(nome) = 'BRENO SANTOS DE OLIVEIRA';
UPDATE colaboradores SET dataNascimento = '1976-07-12' WHERE UPPER(nome) = 'RICARDO DE QUEIROZ RIGUEIRA';
UPDATE colaboradores SET dataNascimento = '2003-08-24' WHERE UPPER(nome) = 'MARIA EDUARDA PAMPONET RAMALHO';
UPDATE colaboradores SET dataNascimento = '2002-07-15' WHERE UPPER(nome) = 'BRUNO NOVAIS DOS SANTOS';
UPDATE colaboradores SET dataNascimento = '1987-08-26' WHERE UPPER(nome) = 'NAIARA DIOGENS SANTOS DA SILVA';
UPDATE colaboradores SET dataNascimento = '1988-07-17' WHERE UPPER(nome) = 'DANIEL BEZERRA DE SOUZA';
UPDATE colaboradores SET dataNascimento = '2004-08-27' WHERE UPPER(nome) = 'LUCAS KELVIM SILVA CASTRO';
UPDATE colaboradores SET dataNascimento = '1974-07-17' WHERE UPPER(nome) = 'JAVIER RODRIGUES PEREZ';
UPDATE colaboradores SET dataNascimento = '2002-08-29' WHERE UPPER(nome) = 'THARLYANNE DA SILVA ROCHA';
UPDATE colaboradores SET dataNascimento = '1994-07-26' WHERE UPPER(nome) = 'GLEDSON SANTIAGO DOS SANTOS';
UPDATE colaboradores SET dataNascimento = '2001-08-30' WHERE UPPER(nome) = 'EMILLY KROLINA DA SILVA FERREIRA';
UPDATE colaboradores SET dataNascimento = '2004-07-26' WHERE UPPER(nome) = 'CAUAN SILVA JESUS';
UPDATE colaboradores SET dataNascimento = '2000-07-29' WHERE UPPER(nome) = 'JORDAN VARJÃO DIAS';
UPDATE colaboradores SET dataNascimento = '1999-07-31' WHERE UPPER(nome) = 'JOÂO ALEXANDRE NASCIMENTO PINTO';
UPDATE colaboradores SET dataNascimento = '2000-07-31' WHERE UPPER(nome) = 'WILLIAN SILVA SOUZA';
UPDATE colaboradores SET dataNascimento = '1981-09-03' WHERE UPPER(nome) = 'DANIEL SILVA NAVARRO';
UPDATE colaboradores SET dataNascimento = '1996-10-01' WHERE UPPER(nome) = 'ADRIELLE DOS SANTOS NASCIMENTO';
UPDATE colaboradores SET dataNascimento = '1987-09-07' WHERE UPPER(nome) = 'JACKSON ARAUJO DE JESUS SILVA';
UPDATE colaboradores SET dataNascimento = '2003-10-02' WHERE UPPER(nome) = 'SUELISON DOS SANTOS ROSA';
UPDATE colaboradores SET dataNascimento = '1980-09-11' WHERE UPPER(nome) = 'PERTERSON SOUZA ALBURQUERQUE';
UPDATE colaboradores SET dataNascimento = '2025-10-02' WHERE UPPER(nome) = 'TIAGO DE AMORIM DIAS';
UPDATE colaboradores SET dataNascimento = '1984-09-11' WHERE UPPER(nome) = 'CLECIA DIAS SANTOS MARQUES SILVA';
UPDATE colaboradores SET dataNascimento = '1992-10-04' WHERE UPPER(nome) = 'ERE BARBOSA DE FREITAS MATOS';
UPDATE colaboradores SET dataNascimento = '1982-09-12' WHERE UPPER(nome) = 'DIEGO NOVAES DOS ANJOS';
UPDATE colaboradores SET dataNascimento = '2004-10-06' WHERE UPPER(nome) = 'PEDRO VINICIUS TAVARES SANTOS FERREIRA';
UPDATE colaboradores SET dataNascimento = '1976-09-15' WHERE UPPER(nome) = 'IVAN DE JESUS NEVES';
UPDATE colaboradores SET dataNascimento = '1991-10-08' WHERE UPPER(nome) = 'YURI SOUZA LEAO';
UPDATE colaboradores SET dataNascimento = '2003-09-17' WHERE UPPER(nome) = 'HUGO CHAGAS DOS SANTOS MIGUEL';
UPDATE colaboradores SET dataNascimento = '1980-10-11' WHERE UPPER(nome) = 'ANDERSON PEREIRA BATISTA';
UPDATE colaboradores SET dataNascimento = '1981-09-19' WHERE UPPER(nome) = 'LAZARO RAMON DA HORA SANTOS';
UPDATE colaboradores SET dataNascimento = '1999-10-12' WHERE UPPER(nome) = 'LEONARDO TELES XAVIER BRAGA';
UPDATE colaboradores SET dataNascimento = '2006-09-20' WHERE UPPER(nome) = 'ISABELLE MARTA BULHOES BRITO DE JESUS';
UPDATE colaboradores SET dataNascimento = '1966-10-14' WHERE UPPER(nome) = 'WELLINGTON ANDRADE FREIRE';
UPDATE colaboradores SET dataNascimento = '1979-09-23' WHERE UPPER(nome) = 'MARIANA BONFIM ARAUJO SILVA';
UPDATE colaboradores SET dataNascimento = '1979-10-14' WHERE UPPER(nome) = 'JOSE DOS ANJOS BATISTA RIBEIRO';
UPDATE colaboradores SET dataNascimento = '1991-09-25' WHERE UPPER(nome) = 'DANIELLE MARQUES CAZUMBÁ';
UPDATE colaboradores SET dataNascimento = '1994-10-15' WHERE UPPER(nome) = 'GABRIEL SOUZA DA SILVA';
UPDATE colaboradores SET dataNascimento = '1996-09-25' WHERE UPPER(nome) = 'ALAELSON DE JESUS SANTOS JUNIOR';
UPDATE colaboradores SET dataNascimento = '1999-10-15' WHERE UPPER(nome) = 'PAMELA TAIANE AMORIM REGO';
UPDATE colaboradores SET dataNascimento = '1977-09-30' WHERE UPPER(nome) = 'LUCIANO SANTOS SANTANA';
UPDATE colaboradores SET dataNascimento = '1989-10-19' WHERE UPPER(nome) = 'MARIANA MACEDO FIGUEIREDO';
UPDATE colaboradores SET dataNascimento = '1981-10-24' WHERE UPPER(nome) = 'JOSÉ PÉRICLES MONTEIRO GOMES JUNIOR';
UPDATE colaboradores SET dataNascimento = '2005-10-24' WHERE UPPER(nome) = 'CAUÃ VITÓRIO TOSTA DE LIMA';
UPDATE colaboradores SET dataNascimento = '2002-10-25' WHERE UPPER(nome) = 'EDUARDO VARJÃO DIAS';
UPDATE colaboradores SET dataNascimento = '1987-11-01' WHERE UPPER(nome) = 'EWERTON FONTES DA HORA SILVA';
UPDATE colaboradores SET dataNascimento = '1989-10-29' WHERE UPPER(nome) = 'MURILO SILVA SOUZA';
UPDATE colaboradores SET dataNascimento = '1995-11-06' WHERE UPPER(nome) = 'PHELIPE MACEL RIOS DOS SANTOS';
UPDATE colaboradores SET dataNascimento = '2002-10-29' WHERE UPPER(nome) = 'FRANCISCO CARLOS BARRETO CARDOSO';
UPDATE colaboradores SET dataNascimento = '1980-11-07' WHERE UPPER(nome) = 'WELLINGTON WANDERLEY DE MORAES';
UPDATE colaboradores SET dataNascimento = '1993-10-30' WHERE UPPER(nome) = 'JESSICA SILVA DE ASSIS';
UPDATE colaboradores SET dataNascimento = '1996-11-11' WHERE UPPER(nome) = 'ERIK DE MORAIS PINA DE CARVALHO';
UPDATE colaboradores SET dataNascimento = '2003-10-30' WHERE UPPER(nome) = 'RHUAN DE OLIVEIRA COSTA';
UPDATE colaboradores SET dataNascimento = '1997-11-11' WHERE UPPER(nome) = 'THIAGO TELES SILVA';
UPDATE colaboradores SET dataNascimento = '1997-10-30' WHERE UPPER(nome) = 'EMANUEL RENATO PEREIRA DOS REIS';
UPDATE colaboradores SET dataNascimento = '2003-11-14' WHERE UPPER(nome) = 'MARIA EDUARDA SANTOS FAUSTINO';
UPDATE colaboradores SET dataNascimento = '1993-11-20' WHERE UPPER(nome) = 'MERCIA DE JESUS PEREIRA';
UPDATE colaboradores SET dataNascimento = '1969-11-21' WHERE UPPER(nome) = 'ADRIANO BORGES COSTA';
UPDATE colaboradores SET dataNascimento = '1981-12-01' WHERE UPPER(nome) = 'ANTONIETA QUEIROZ DE SOUZA';
UPDATE colaboradores SET dataNascimento = '2002-11-21' WHERE UPPER(nome) = 'ADRIANA MARIA BISPO SANTOS';
UPDATE colaboradores SET dataNascimento = '1993-12-01' WHERE UPPER(nome) = 'LAIANE MENEZES ARAUJO';
UPDATE colaboradores SET dataNascimento = '2002-11-22' WHERE UPPER(nome) = 'GABRIEL BARRETO SANTIAGO DOS SANTOS';
UPDATE colaboradores SET dataNascimento = '2000-12-01' WHERE UPPER(nome) = 'BRUNO ARAUJO RAMOS SANTOS';
UPDATE colaboradores SET dataNascimento = '2025-11-23' WHERE UPPER(nome) = 'MARCOS SANTOS DA MOTA';
UPDATE colaboradores SET dataNascimento = '1988-12-02' WHERE UPPER(nome) = 'JOSE EDUARDO BARBOSA DE CARVALHO';
UPDATE colaboradores SET dataNascimento = '2003-11-24' WHERE UPPER(nome) = 'SILENIO VIANA LEITE NETO';
UPDATE colaboradores SET dataNascimento = '1973-12-02' WHERE UPPER(nome) = 'SILVIA UCHOA LINS';
UPDATE colaboradores SET dataNascimento = '1995-11-28' WHERE UPPER(nome) = 'IGOR SANTOS SILVA';
UPDATE colaboradores SET dataNascimento = '1999-12-02' WHERE UPPER(nome) = 'ELTON ALMEIDA DE JESUS';
UPDATE colaboradores SET dataNascimento = '1977-11-28' WHERE UPPER(nome) = 'WASHINGTON LUIZ ALVES';
UPDATE colaboradores SET dataNascimento = '1986-12-09' WHERE UPPER(nome) = 'TIAGO DE BARROS MEIRELES';
UPDATE colaboradores SET dataNascimento = '2002-11-28' WHERE UPPER(nome) = 'CICERO RICARDO FARIAS DE LIMA JUNIOR';
UPDATE colaboradores SET dataNascimento = '1986-12-13' WHERE UPPER(nome) = 'THIAGO KELLYSSON BARROS DA ROCHA SILVA';
UPDATE colaboradores SET dataNascimento = '1993-11-29' WHERE UPPER(nome) = 'JOALAS ANDRADE FONTES';
UPDATE colaboradores SET dataNascimento = '1969-12-15' WHERE UPPER(nome) = 'LUIZ WINNTON GUIMARAES CAMARA';
UPDATE colaboradores SET dataNascimento = '1997-12-16' WHERE UPPER(nome) = 'ISIS TEIXEIRA E SILVA';
UPDATE colaboradores SET dataNascimento = '2003-12-18' WHERE UPPER(nome) = 'MARIANA DE ALMEIDA MOURA';
UPDATE colaboradores SET dataNascimento = '2003-12-19' WHERE UPPER(nome) = 'ARNALDO DE LIRO LOPES';
UPDATE colaboradores SET dataNascimento = '1978-12-19' WHERE UPPER(nome) = 'GEORGE DIAS PEREIRA';
UPDATE colaboradores SET dataNascimento = '1981-12-21' WHERE UPPER(nome) = 'ANA CAROLINA ASSIS DE ALMEIDA';
UPDATE colaboradores SET dataNascimento = '2003-12-23' WHERE UPPER(nome) = 'CAUA GOES FARIAS';
UPDATE colaboradores SET dataNascimento = '1997-12-23' WHERE UPPER(nome) = 'IURY ROQUE';
UPDATE colaboradores SET dataNascimento = '1999-12-27' WHERE UPPER(nome) = 'GUSTAVO BARBOSA DOS SANTOS';
UPDATE colaboradores SET dataNascimento = '1986-12-30' WHERE UPPER(nome) = 'RAFAELA OLIVEIRA ARAUJO';
UPDATE colaboradores SET dataNascimento = '1973-12-30' WHERE UPPER(nome) = 'GABRIEL AGUADE DO COUTO';
